
const PAYSTACK_PUBLIC_KEY = 'pk_live_4b90f71093f9c9db50874031742c77d0feb69428';
const KEY={cart:'gc_cart',fav:'gc_fav',orders:'gc_orders',user:'gc_user'};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function currentUser(){return load(KEY.user,null)} function requireAuth(next='checkout.html'){if(!currentUser()){location.href=`login.html?next=${encodeURIComponent(next)}`;return false}return true}
function cart(){return load(KEY.cart,[])} function favs(){return load(KEY.fav,[])}
function addCart(id,qty=1){const c=cart();const x=c.find(i=>i.id==id);if(x)x.qty+=qty;else c.push({id:Number(id),qty});save(KEY.cart,c);updateCounts();return c}
function removeCart(id){save(KEY.cart,cart().filter(x=>x.id!=id));updateCounts();renderCart?.()}
function changeQty(id,delta){const c=cart();const x=c.find(i=>i.id==id);if(x){x.qty=Math.max(1,x.qty+delta);save(KEY.cart,c)}updateCounts();renderCart?.()}
function toggleFavorite(id){const f=favs();const n=Number(id);const i=f.indexOf(n);if(i>=0)f.splice(i,1);else f.push(n);save(KEY.fav,f);updateCounts();if(location.pathname.endsWith('favorites.html'))renderFavorites()}
function updateCounts(){const cc=cart().reduce((a,b)=>a+b.qty,0);document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cc);document.querySelectorAll('[data-fav-count]').forEach(e=>e.textContent=favs().length);const u=currentUser();document.querySelectorAll('[data-user]').forEach(e=>e.textContent=u?u.name:'Sign in')}
function moneyTotal(){return cart().reduce((s,x)=>s+GhanaCart.getProduct(x.id).price*x.qty,0)}
function nav(){document.querySelectorAll('[data-nav-search]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const q=f.querySelector('input').value.trim();location.href=`search.html?q=${encodeURIComponent(q)}`}));updateCounts()}
function productPage(){const id=new URLSearchParams(location.search).get('id')||'1';const p=GhanaCart.getProduct(id);document.title=`${p.name} | GhanaCart`;document.querySelector('#product').innerHTML=`<div>${GhanaCart.imagePlaceholder(p,true)}</div><div><div class="meta">${p.department} · SKU GC-${String(p.id).padStart(8,'0')}</div><h1>${GhanaCart.escapeHtml(p.name)}</h1><p class="muted">${GhanaCart.escapeHtml(p.short)}</p><div><span class="price">${GhanaCart.money(p.price)}</span>${p.old?` <span class="old">${GhanaCart.money(p.old)}</span>`:''}</div><div class="actions">${p.discount?`<span class="tag orange">${p.discount}% discount</span>`:''}${p.freeShipping?`<span class="tag">Free shipping</span>`:''}</div><p>${GhanaCart.escapeHtml(p.description)}</p><div class="specs"><div class="spec"><b>Size</b><br>${p.size}</div><div class="spec"><b>Material</b><br>${p.material}</div><div class="spec"><b>Feature</b><br>${p.feature}</div><div class="spec"><b>Stock</b><br>${p.stock} units</div><div class="spec"><b>Delivery</b><br>${p.deliveryDays}–${p.deliveryDays+2} days</div><div class="spec"><b>Image filename</b><br><small>${p.imageName}</small></div></div><div class="actions"><button class="btn primary" onclick="addCart(${p.id});location.href='cart.html'">Add to cart</button><button class="btn secondary" onclick="toggleFavorite(${p.id})">♡ Favorite</button></div><div class="notice" style="margin-top:15px">Order requires sign-in. Ghana delivery is available by region/town at checkout.</div></div>`}
function renderListing(){const params=new URLSearchParams(location.search);const q=params.get('q')||'';const category=params.get('category')||'';const page=Math.max(1,Number(params.get('page')||1));let items=[];try{items=GhanaCart.searchProducts(q||category,page,20)||[]}catch(e){console.error('Search error',e)}if(category)items=items.filter(p=>p.departmentKey===category||p.department.toLowerCase().includes(category.toLowerCase())).slice(0,20);document.querySelector('#listingTitle').textContent=q?`Search results for “${q}”`:category?GhanaCart.DEPARTMENTS[category]?.name||'Category':'All products';document.querySelector('#listingMeta').textContent=`20,000,000+ catalog listings · page ${page}`;const grid=document.querySelector('#grid');if(grid)grid.innerHTML=items.length?items.map(GhanaCart.productCard).join(''):`<div class="empty search-empty"><div class="search-icon">🔎</div><h2>${q?`No products found for “${GhanaCart.escapeHtml(q)}”`:'Browse GhanaCart products'}</h2><p class="muted">Try searching for phones, blenders, shoes, clothes, laptops or other items.</p><a class="btn primary" href="categories.html">Shop categories</a></div>`;const pages=document.querySelector('#pages');if(pages)pages.innerHTML=[page-1,page,page+1,page+2].filter(x=>x>0).map(x=>`<button class="${x===page?'active':''}" onclick="location.href='search.html?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&page=${x}'">${x}</button>`).join('')}
function renderCart(){const el=document.querySelector('#cartItems');if(!el)return;const c=cart();if(!c.length){el.innerHTML=`<div class="empty"><h2>Your cart is empty</h2><p class="muted">Browse millions of products and add something you like.</p><a class="btn primary" href="index.html">Start shopping</a></div>`;document.querySelector('#subtotal').textContent=GhanaCart.money(0);return}el.innerHTML=c.map(x=>{const p=GhanaCart.getProduct(x.id);return `<div class="cartrow"><div class="cartpic"><img src="${GhanaCart.imageUrl(p)}" alt="${GhanaCart.escapeHtml(p.name)}" loading="lazy"></div><div><a href="product.html?id=${p.id}"><b>${GhanaCart.escapeHtml(p.name)}</b></a><div class="meta">${p.feature} · ${p.freeShipping?'Free shipping':'Standard shipping'}</div><button class="btn danger" onclick="removeCart(${p.id})">Remove</button></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div><b>${GhanaCart.money(p.price*x.qty)}</b></div>`}).join('');document.querySelector('#subtotal').textContent=GhanaCart.money(moneyTotal())}
function renderFavorites(){const el=document.querySelector('#favGrid');const f=favs();el.innerHTML=f.length?f.map(id=>GhanaCart.productCard(GhanaCart.getProduct(id))).join(''):`<div class="empty"><h2>No favorites yet</h2><p class="muted">Tap ♡ on any product to save it here.</p><a class="btn primary" href="index.html">Browse products</a></div>`}
function renderHome(){const grid=document.querySelector('#homeGrid');if(!grid)return;const arr=Array.from({length:20},(_,i)=>GhanaCart.getProduct(i+1));grid.innerHTML=arr.map(GhanaCart.productCard).join('');const strip=document.querySelector('#swipeTrack');if(strip){const swipe=Array.from({length:12},(_,i)=>GhanaCart.getProduct(i+31));strip.innerHTML=swipe.concat(swipe).map(p=>`<a class="swipe-item" href="product.html?id=${p.id}"><img src="${GhanaCart.imageUrl(p)}" alt="${GhanaCart.escapeHtml(p.name)}"><span>${GhanaCart.escapeHtml(p.name)}</span><b>${GhanaCart.money(p.price)}</b></a>`).join('')}document.querySelector('#catalogCount').textContent=GhanaCart.catalogSize().toLocaleString()}
function renderOrders(){const el=document.querySelector('#orders');const os=load(KEY.orders,[]);el.innerHTML=os.length?os.slice().reverse().map(o=>`<div class="panel" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:12px"><b>Order #${o.id}</b><span class="tag">${o.status}</span></div><div class="meta">Placed ${new Date(o.date).toLocaleString()} · ${o.city}, ${o.region}</div><p><b>${GhanaCart.money(o.total)}</b> · ${o.items.length} line item(s) · ETA ${o.eta}</p><div class="actions"><a class="btn primary" href="track.html?id=${o.id}">Track order</a>${o.status==='Received'?`<button class="btn danger" onclick="cancelOrder('${o.id}')">Cancel order</button>`:''}</div></div>`).join(''):`<div class="empty"><h2>No orders yet</h2><a class="btn primary" href="index.html">Shop now</a></div>`}
function cancelOrder(id){const os=load(KEY.orders,[]);const o=os.find(x=>x.id===id);if(o){o.status='Cancelled';save(KEY.orders,os);renderOrders()}}
function checkoutPage(){if(!requireAuth())return;const user=currentUser();document.querySelector('#customerEmail').value=user.email||'';const total=moneyTotal();document.querySelector('#checkoutTotal').textContent=GhanaCart.money(total);const regions=Object.keys(GhanaCart.REGIONS);document.querySelector('#region').innerHTML=regions.map(r=>`<option>${r}</option>`).join('');updateTowns();document.querySelector('#checkout').addEventListener('submit',e=>{e.preventDefault();if(!cart().length){alert('Your cart is empty.');return}const fd=new FormData(e.target);const email=fd.get('email');const amount=Math.round(total*100);if(typeof PaystackPop==='undefined'){alert('Paystack could not load. Please check your internet connection and try again.');return}const handler=PaystackPop.setup({key:PAYSTACK_PUBLIC_KEY,email:email,amount:amount,currency:'GHS',ref:'GC-'+Date.now(),metadata:{custom_fields:[{display_name:'Customer phone',variable_name:'phone',value:String(fd.get('phone'))},{display_name:'Delivery town',variable_name:'town',value:String(fd.get('city'))}]},callback:function(response){const order={id:'GC'+Date.now().toString().slice(-9),date:new Date().toISOString(),status:'Paid',reference:response.reference,email:email,phone:fd.get('phone'),region:fd.get('region'),city:fd.get('city'),address:fd.get('address'),payment:'Paystack',total:total,items:cart(),eta:new Date(Date.now()+(3*864e5)).toLocaleDateString('en-GH',{weekday:'short',day:'numeric',month:'short',year:'numeric'})};const os=load(KEY.orders,[]);os.push(order);save(KEY.orders,os);save(KEY.cart,[]);location.href=`order-success.html?id=${order.id}`},onClose:function(){}});handler.openIframe()})}
function updateTowns(){const r=document.querySelector('#region')?.value;const s=document.querySelector('#city');if(s)s.innerHTML=(GhanaCart.REGIONS[r]||[]).filter(x=>!x.includes('?')).map(c=>`<option>${c}</option>`).join('')}
function authPage(){const form=document.querySelector('#authForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const email=String(fd.get('email')||'').trim();const name=String(fd.get('name')||email.split('@')[0]||'Customer').trim();if(!email)return;save(KEY.user,{name,email});const next=new URLSearchParams(location.search).get('next')||'index.html';location.href=next})}
function successPage(){const id=new URLSearchParams(location.search).get('id');const o=load(KEY.orders,[]).find(x=>x.id===id);if(!o){document.querySelector('#success').innerHTML='<div class="panel"><h1>Order not found</h1><a class="btn primary" href="orders.html">View orders</a></div>';return}document.querySelector('#success').innerHTML=`<div class="panel" style="text-align:center"><div style="font-size:60px">✅</div><h1>Order received</h1><p>Your order <b>#${o.id}</b> has been received successfully.</p><div class="notice">Estimated arrival: <b>${o.eta}</b></div><div class="actions" style="justify-content:center"><a class="btn primary" href="track.html?id=${o.id}">Track order</a><a class="btn secondary" href="orders.html">Order history</a><a class="btn orange" href="index.html">Continue shopping</a></div></div>`}
function trackPage(){const id=new URLSearchParams(location.search).get('id');const o=load(KEY.orders,[]).find(x=>x.id===id);const el=document.querySelector('#tracking');if(!o){el.innerHTML='<div class="panel"><h2>Enter an order from your order history.</h2><a class="btn primary" href="orders.html">Open orders</a></div>';return}el.innerHTML=`<div class="panel"><h1>Track #${o.id}</h1><p>${o.city}, ${o.region} · ETA <b>${o.eta}</b></p><div class="timeline"><div class="step"><b>Order received</b><div class="muted">Payment confirmation recorded.</div></div><div class="step"><b>Preparing your items</b><div class="muted">Seller is preparing your parcel.</div></div><div class="step"><b>Dispatched to Ghana delivery network</b><div class="muted">Your parcel is moving to the selected location.</div></div><div class="step"><b>Out for delivery</b><div class="muted">Courier will contact you.</div></div><div class="step"><b>Delivered</b><div class="muted">Delivery confirmation.</div></div></div></div>`}
function addBackButton(){if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/'))return;const main=document.querySelector('main.main');if(!main||main.querySelector('.backbar'))return;const bar=document.createElement('div');bar.className='backbar';bar.innerHTML='<button class="btn secondary backbtn" type="button">← Back</button>';bar.querySelector('button').addEventListener('click',()=>history.length>1?history.back():location.href='index.html');main.prepend(bar)}
function init(){nav();addBackButton();const p=location.pathname.split('/').pop()||'index.html';if(p==='index.html'||p==='')renderHome();if(p==='product.html')productPage();if(p==='search.html'||p==='category.html')renderListing();if(p==='cart.html')renderCart();if(p==='favorites.html')renderFavorites();if(p==='checkout.html')checkoutPage();if(p==='orders.html')renderOrders();if(p==='order-success.html')successPage();if(p==='track.html')trackPage();if(p==='login.html'||p==='signup.html')authPage();document.querySelector('#region')?.addEventListener('change',updateTowns);document.querySelectorAll('[data-require-auth]').forEach(a=>a.addEventListener('click',e=>{if(!requireAuth(a.getAttribute('href')||'checkout.html'))e.preventDefault()}));}
document.addEventListener('DOMContentLoaded',init);
window.addCart=addCart;window.removeCart=removeCart;window.changeQty=changeQty;window.toggleFavorite=toggleFavorite;window.cancelOrder=cancelOrder;window.updateTowns=updateTowns;window.requireAuth=requireAuth;
